apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-website-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: blog-webapp
  template:
    metadata:
      labels:
        app: blog-webapp
    spec:
      containers:
      - name: blog-webapp
        image: yash5090/blog-webapp:latest
        ports:
        - containerPort: 5000
